FROM golang:1.21-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o backend1 ./backends/backend1.go
RUN CGO_ENABLED=0 GOOS=linux go build -o backend2 ./backends/backend2.go
RUN CGO_ENABLED=0 GOOS=linux go build -o backend3 ./backends/backend3.go

FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/backend1 .
COPY --from=builder /app/backend2 .
COPY --from=builder /app/backend3 .
